restaurant_waiter/config/routes.rb
RestaurantWaiter::Application.routes.draw do
get "/websocket", :to => WebsocketRails::ConnectionManager.new
resources :roles, path: '6S2C2585/superadmin/roles'
devise_for :super_admins, :controllers => {:sessions=>"super_admin/sessions",:passwords=>"super_admin/passwords", :registrations=>'super_admin/registrations'}, path: '6S2C2585/superadmin'
  devise_scope :super_admin  do
    scope "6S2C2585/superadmin", :module => 'super_admin' do
      resources :ads_subscriptions
      get '/' => 'sessions#new'
      get '/paid_admins' => 'admin#index', :as => :all_admin_index
      put '/update' => 'admin#update', :as => :update_restaurant_status
      get '/ad_control' => 'admin#ad_controller', :as => :ad_control
      get '/get_city' => 'admin#get_city', :as => :get_city
      get '/get_restaurantdetails' => 'admin#get_restaurantdetails', :as => :get_restaurantdetails
      get '/get_adsdetails' => 'admin#get_adsdetails', :as => :get_adsdetails
      post '/ad_settings' => 'admin#ad_settings', :as => :ad_settings
      delete '/ad_destroy/:id' => 'admin#ad_settings', :as => :ad_destroy
      get '/view_customers' => 'admin#view_customers', :as => :view_customers
      get '/new_customers' => 'admin#new_customers', :as => :new_customers
      put '/update_admin_status/:id' => 'admin#update_admin_status', :as => :update_admin
      get '/get_notification' => 'admin#get_notification', :as => :get_notifications

      get '/report' => 'report#report', :as => :report
      get '/report/restaurant_report' => 'report#restaurant_report', :as => :restaurant_report
      get '/subregion_options' => 'report#subregion_options', :as => :country_subregion_for_report
      get '/report/subregion_options' => 'report#subregion_options', :as => :report_get_subregion_options
      get '/report/get_city' => 'report#get_city', :as => :report_get_city
      get '/report/get_restaurant' => 'report#get_restaurant', :as => :report_get_restaurant

      get '/report/get_graphs' => 'report#get_graphs', :as => :report_get_graphs
      get '/report/get_restaurants_graphs' => 'report#get_restaurants_graphs', :as => :report_get_restaurants_graphs
    end
  end

=begin
routes for admin starts here
=end
  devise_for :admins, :controllers => {:registrations=>"admin/registrations",:sessions=>"admin/sessions",:passwords=>"admin/passwords"}, path: '6S1D0518/admins'
  devise_scope :admin do
    get '/admins' => 'admin/registrations#new', as: 'new_admin'
    get '/admins/subregion_options' => 'admin/registrations#subregion_options'
  end
   get "/6S1D0518/admins/", :to=> "admin/sessions#new"
   get "/admins/sign_in", :to=> "admin/sessions#new"
   get "admins/manageoptions",:to =>"admin/templates#manageoptions"
   post "admins/manageoptions",:to =>"admin/templates#manageoptions"
   post "admins/updateoptions",:to =>"admin/templates#updateoptions" ,:as => :create

   get "/admins/template",:to =>"admin/templates#uploadtemplate"
   get "/admins/download_template",:to =>"admin/templates#downloadtemplate"
   post "admins/upload",:to =>"admin/templates#upload" #upload excel file
   post "admins/uploadallimages",:to =>"admin/templates#uploadallimages" 
   post "/admins/getcategorycount", :to => "admin/templates#getcategorycount"

   get "/admins/allcategories",:to =>"admin/categories#allcategories"
   post "/admins/allcategories",:to =>"admin/categories#allcategories"
   post "/admins/addcategory",:to =>"admin/categories#addcategory" #add new category
   post "/admins/deletecategory",:to =>"admin/categories#deletecategory" #delete a category
   post "admins/getcategoryinfo", :to => "admin/categories#getcategoryinfo" #get category info
   post "/admins/updatecategory", :to => "admin/categories#updatecategory" #update a category
   

   get "/admins/drinks",:to =>"admin/categories#drinks"
   post "/admins/adddrinkcategory",:to =>"admin/categories#adddrinkcategory"
   post "/admins/deletedrinkcategory",:to =>"admin/categories#deletedrinkcategory"
   get "/admins/drinkdetail", :to => "admin/categories#drinkdetail"
   post "/admins/deletedrink", :to => "admin/categories#deletedrink"
   post "/admins/adddrink", :to => "admin/categories#adddrink"
    post "/admins/updatedrink", :to => "admin/categories#updatedrink"
   post "/admins/getdrinkcategoryinfo", :to => "admin/categories#getdrinkcategoryinfo"
    post "/admins/updatedrinkcategory", :to => "admin/categories#updatedrinkcategory"
   

   get "admins/categorydetail",:to =>"admin/categories#categorydetail"
   post "/admins/addfooditem",:to =>"admin/categories#addfooditem"
   post "/admins/deletefooditem",:to =>"admin/categories#deletefooditem"
    post "/admins/updatefooditem",:to =>"admin/categories#updatefooditem"

   get "/admins/extrasdetail",:to =>"admin/categories#extrasdetail"
  post "/admins/addextras",:to =>"admin/categories#addextras"
  post "/admins/deleteextras",:to =>"admin/categories#deleteextras"
   post "/admins/updateextras",:to =>"admin/categories#updateextras"

   get "/admins/extrasdetail",:to =>"admin/categories#extrasdetail"
  post "/admins/addextras",:to =>"admin/categories#addextras"
  post "/admins/deleteextras",:to =>"admin/categories#deleteextras"
   
   
  get "/admins/settings",:to =>"admin/settings#restaurantsettings"
  get "/admins/othersettings",:to =>"admin/settings#othersettings"
  get "admins/adsubscription",:to =>"admin/settings#adsubscription"
  get "/admins/alladvertisements",:to =>"admin/settings#alladvertisements"
  post "/admins/alladvertisements",:to =>"admin/settings#alladvertisements"
  post "/admins/updatekitchentime",:to =>"admin/settings#updatekitchentime"
  post "/admins/updatebartime",:to =>"admin/settings#updatebartime"
  post "/admins/updatehappyhourtime",:to =>"admin/settings#updatehappyhourtime"
  post "/admins/addadvertisement",:to =>"admin/settings#addadvertisement"
  post "/admins/deleteadvertisement",:to =>"admin/settings#deleteadvertisement"
  post "/admins/disableadvertisement",:to =>"admin/settings#disableadvertisement"
  post "/admins/enableadvertisement",:to =>"admin/settings#enableadvertisement"
  post "/admins/updatesettingoptions",:to =>"admin/settings#updatesettingoptions"
  post "/admins/updaterestaurantoptions",:to =>"admin/settings#updaterestaurantoptions"
  post "/admins/paybill",:to =>"admin/settings#paybill"
  post "/admins/updatesubscription",:to =>"admin/settings#updatesubscription"
  post "/admins/updatetransactionid",:to =>"admin/settings#updatetransactionid"
  get '/admins/state_options' => 'admin/settings#state_options'
  post '/admins/makepayment' => 'admin/settings#makepayment'
  get  '/admins/paymentdetails'=>'admin/settings#paymentdetails'
  
  post "/admins/forgotpassword",:to =>"admin/settings#forgotpassword"
  get "admins/settings/resetpassword", :to => "admin/settings#resetpassword"
  post "/admins/makesubscription", :to => "admin/settings#makesubscription"
  
=begin
routes for app starts here
=end
   
   
   
   
   
   
  devise_for :users, :controllers => {:registrations => "registrations",:sessions=>"sessions",:passwords=>"passwords"}

   root 'admin/sessions#new'

  get "/allcategories/getallcategories", :to => "allcategories#getallcategories"

  post "/allcategories/getallcategories", :to => "allcategories#getcategories"

  post "/allcategories/getfooditemsincategory", :to => "allcategories#getfooditemsincategory"

  post "/allcategories/getfooditemsdetails", :to => "allcategories#getfooditemsdetails"

  post "/allcategories/getextraslist", :to => "allcategories#getextraslist"

  post "/allcategories/getextrasdetails", :to => "allcategories#getextrasdetails"

  get "/drinkdetails", :to => "drinks#drinkdetails"

  post "/drinkdetails/getalldrinkcategories", :to => "drinks#getalldrinkcategories"

  post "/drinkdetails/getalldrinks", :to => "drinks#getalldrinks"

  post "/drinkdetails/getdrinkdetail", :to => "drinks#getdrinkdetail"

  get "/restaurantdetails", :to => "allrestaurants#restaurantdetails"

  post "/restaurantdetails/getrestaurantlist", :to => "allrestaurants#getrestaurantlist"

  post "/restaurantdetails/getrestaurantdetail", :to => "allrestaurants#getrestaurantdetail"

  post "/restaurantdetails/getqrcode", :to => "allrestaurants#getqrcode"
  
  post "/restaurantdetails/getrestaurantdetailfromgimbal", :to => "allrestaurants#getrestaurantdetailfromgimbal"
  
  post "/restaurantdetails/sendnotifications", :to => "allrestaurants#sendnotifications"
  
  get "/restaurantdetails/getcurrenttime", :to => "allrestaurants#getcurrenttime"
  

  get "/orderdetails", :to => "orders#orderdetails"

  post "/orderdetails/addorder", :to => "orders#addorder"

  post "/orderdetails/revieworder", :to => "orders#revieworder"

  post "/orderdetails/confirmorder", :to => "orders#confirmorder"

  post "/orderdetails/history", :to => "orders#history"

  post "/orderdetails/checkrestauranttimings", :to => "orders#checkrestauranttimings"
  
  post "/orderdetails/paylaterhistory", :to => "orders#paylaterhistory"
  
  get "/userdetails", :to => "userinfo#getuserdetails"

  post "/userinfo/getuserinfo", :to => "userinfo#getuserinfo"

  post "/userinfo/uploadimage", :to => "userinfo#uploadimage"

  post "/userinfo/accesstokenlogin", :to => "userinfo#accesstokenlogin"

  post "/userinfo/forgotpassword", :to => "userinfo#forgotpassword"

  get "/userinfo/resetpassword", :to => "userinfo#resetpassword"

  post "/userinfo/updatepassword", :to => "userinfo#updatepassword"

  get "/paymentdetails", :to => "payment#paymentdetails"

  post "/payment/paymenttransactions", :to => "payment#paymenttransactions"

  post "/payment/getcardlist", :to => "payment#getcardlist"

  post "/payment/addcardnumber", :to => "payment#addcardnumber"

  post "/payment/setdefaultcard", :to => "payment#setdefaultcard"

  post "/payment/deletecard", :to => "payment#deletecard"
  
  post "/payment/updatetipinfo", :to => "payment#updatetipinfo"

  get  "/payment/paylater", :to => "payment#paylater"
  
  get "/ad_details", :to => "advertisements#ad_details"
  

restaurant_waiter/app/models/super_admin.rb
class SuperAdmin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  belongs_to :role

  def has_role?(role)
    self.role.name.parameterize.underscore.to_sym ==  role rescue false
  end
end

restaurant_waiter/app/controllers/super_admin/admin_controller.rb
class SuperAdmin::AdminController < ApplicationController
  authorize_resource :class => false
  before_filter :authenticate_super_admin!
  before_filter :get_super_admin_notifications
  before_filter :define_instance_variables, :only => [:view_customers, :new_customers]
  layout 'admin_dashboard'

  def index
    @confirm_class= 'active'
    @restaurants = Restaurantdetail.find_by_sql("Select DISTINCT * from restaurantdetails inner join admins on restaurantdetails.id= admins.restaurant_id where admins.is_paid=1")
    render :template => 'super_admin/index'
  end

  def update
    admin = Admin.where(:id=> params[:id]).first
    admin.update_attributes(:confirm_status => params[:status],:amount_paid => (params[:status]=="0" ? "" : params[:amount_paid]), :amount_paid_date => DateTime.now) unless admin.nil?
    SuperAdminMailer.send_confirmation_mail(admin).deliver if admin.confirm_status
    WebsocketRails[:posts].trigger 'new', admin  if admin.confirm_status
    render :json => {:success => admin.confirm_status.to_s}
  end

  def ad_controller
    @ads_class = 'active'
    @cities =[]
    @ads =[]
    @restaurants =[]
    render :template => 'super_admin/ads'
  end

  def get_city
    @cities = Restaurantdetail.where(:state => params[:state], :country => params[:country]).select("city").uniq
    render :partial => 'super_admin/city_detail'
  end

  def get_restaurantdetails
    @restaurants = Restaurantdetail.where(:state => params[:state], :country => params[:country], :city => params[:city]).uniq
    render :partial => 'super_admin/restaurant_detail'
  end

  def get_adsdetails
    @ads = Advertisement.where(:restaurant_id => params[:id]) rescue []
    render :partial => 'super_admin/ad_details'
  end

  def ad_settings
    if request.method=='POST'
      ad = Advertisement.where("id=?", params[:id]).first
      updated = ad.update_attributes(:ad_settings => (params[:ad_setting]=="0" ? 1 : 0))
      respond_to do |format|
        if updated
          #flash[:notice]= "Advertisement has been updated successfully."
          format.html {redirect_to :back}
          format.json {render :json => {:success => true, :settings => ad.ad_settings}}
        else
          #flash[:error]= "Unable to delete advertisement, please try again after some time."
          format.html {redirect_to :back}
          format.json {render :json => {:success => false, :settings => ad.ad_settings}}
        end
      end
    else
      isDeleted=Advertisement.find_by_id(params[:id]).destroy
      respond_to do |format|
      if isDeleted
          #flash[:notice]= "Advertisement has been deleted successfully."
          format.html {redirect_to :back}
          format.json {render :json => {:success => true}}
      else
          flash[:error]= "Unable to delete advertisement, please try again after some time."
          format.html {redirect_to :back}
          format.json {render :json => {:success => false}}
        end
      end
    end
  end

  def view_customers
    @ec = 'active'      # @ec implies Existing Customer
    @restaurants = Restaurantdetail.find_by_sql("Select DISTINCT * from restaurantdetails inner join admins on admins.restaurant_id=restaurantdetails.id where admins.is_paid=1 and admins.confirm_status=1")
    render :template => 'super_admin/customers'
  end

  def new_customers
    @nc = 'active'      # @nc implies Existing Customer
    @restaurants = Restaurantdetail.find_by_sql("Select DISTINCT * from restaurantdetails inner join admins on admins.restaurant_id=restaurantdetails.id where admins.is_paid=0 and admins.confirm_status=0")
    render :template => 'super_admin/customers'
  end

  def update_admin_status
    admin = Admin.where(:id=>params[:id]).first
    admin.update_attributes(:active => (admin.active ? false : true))
    render :json => {:success => true ,:confirmed => admin.active}
  end

  def get_notification
    render :partial => 'super_admin/shared/notification'
  end

  private

  def define_instance_variables
    @customer_open = 'open'
    @customer_block = 'block'
    @li_active = 'active'
  end
end

restaurant_waiter/app/controllers/super_admin/ads_subscriptions_controller.rb
class SuperAdmin::AdsSubscriptionsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_super_admin!
  before_filter :get_super_admin_notifications
  before_action :set_super_admin_ads_subscription, only: [:show, :edit, :update, :destroy]

  layout 'admin_dashboard'

  # GET /super_admin/ads_subscriptions
  # GET /super_admin/ads_subscriptions.json
  def index
    @subscription_class = 'active'
    @super_admin_ads_subscriptions = AdsSubscription.all
  end

  # GET /super_admin/ads_subscriptions/1
  # GET /super_admin/ads_subscriptions/1.json
  def show
  end

  # GET /super_admin/ads_subscriptions/new
  def new
    @super_admin_ads_subscription = AdsSubscription.new
  end

  # GET /super_admin/ads_subscriptions/1/edit
  def edit
  end

  # POST /super_admin/ads_subscriptions
  # POST /super_admin/ads_subscriptions.json
  def create
    @super_admin_ads_subscription = AdsSubscription.new(super_admin_ads_subscription_params)

    respond_to do |format|
      if @super_admin_ads_subscription.save
        format.html { redirect_to @super_admin_ads_subscription, notice: 'Ads subscription was successfully created.' }
        format.json { render :json => {:success => true, :ad_id => @super_admin_ads_subscription.id} }
      else
        format.html { render action: 'new' }
        format.json { render :json => {:success => false} }
      end
    end
  end

  # PATCH/PUT /super_admin/ads_subscriptions/1
  # PATCH/PUT /super_admin/ads_subscriptions/1.json
  def update
    respond_to do |format|
      if @super_admin_ads_subscription.update(super_admin_ads_subscription_params)
        format.html { redirect_to @super_admin_ads_subscription, notice: 'Ads subscription was successfully updated.' }
        format.json { render :json => {:success => true} }
      else
        format.html { render action: 'edit' }
        format.json { render :json => {:success => false} }
      end
    end
  end

  # DELETE /super_admin/ads_subscriptions/1
  # DELETE /super_admin/ads_subscriptions/1.json
  def destroy
    @super_admin_ads_subscription.destroy
    respond_to do |format|
      format.html { redirect_to super_admin_ads_subscriptions_url }
      format.json { render :json => {:success => true} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_super_admin_ads_subscription
      @super_admin_ads_subscription = AdsSubscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def super_admin_ads_subscription_params
      params[:super_admin_ads_subscription].permit([:name, :ad_type, :price, :id, :short_name, :no_of_days])
    end
end

restaurant_waiter/app/views/super_admin/_ad_details.html.erb
<style>
  .make_line{
      display: inline-flex;
  }
</style>
<section class="panel">
  <div class="adv-table">
  <table class="display table table-bordered" id="superadmin_ads_table">
    <thead>
    <tr>
      <th style="text-align: center"><i class=''></i>Ads</th>
      <th style="text-align: center"><i class=""></i> Descrition</th>
      <th style="text-align: center"><i class=""></i>Status</th>
    </tr>
    </thead>
    <tbody>
    <% @ads.each do |ad| %>
    <tr>
      <td style="width: 33%;text-align: center;">
        <div class="col-lg-3"><% if ad.ad_type == 1 %>
            <img src="<%= ad.avatar.url(:medium) %>" alt="Nature Portfolio" style=" border-radius: 25px; width: 120px; height: 120px;"/>
        <% else %>
            <video controls style="border-radius: 25px;">
              <source src="<%= ad.avatar.url %>" type="video/mp4">
            </video>
        <% end %>
        </div>
      </td>
      <td style="text-align: center;"><span class="label label-info label-mini"><%= ad.ads_subscription.name rescue ''%></span></td>
      <td style="text-align: center;">
         <%= button_to(ad_settings_path(:id => ad.id, :ad_setting => ad.ad_settings), :form_class => "make_line", :class => 'btn btn-success btn-xs', :id=> 'super_admin_ad_form') do %>
               <i class="icon-off"></i> <%= ad.ad_settings==1 ? 'Disable' : 'Enable' %>
            <%= hidden_field_tag('ad_id',  ad.id, :id=> 'ad_id' ) %>
            <%= hidden_field_tag('ad_setting',  ad.ad_settings, :id=> 'ad_setting' ) %>
        <% end %>
        <%= button_to(ad_destroy_path(:id => ad.id), :form_class => "make_line", :class => 'btn btn-danger btn-xs',:id=> 'super_admin_ad_destroy_form', :method => 'delete') do %>
            <i class="icon-trash"></i> Delete
            <%= hidden_field_tag('ad_id',  ad.id, :id=> 'ad_id' ) %>
            <%= hidden_field_tag('ad_setting',  ad.ad_settings, :id=> 'ad_setting' ) %>
        <% end %>

      </td>
    </tr>
    <% end %>
      </tbody>
      </table>
  </div>
    </section>

restaurant_waiter/app/views/super_admin/_city_detail.html.erb
<label for="exampleInputEmail1">City</label>
<%= select_tag 'restaurantdetail_city', options_for_select(@cities.collect{ |u| [u.city] }), {:prompt => 'Select City', :class => 'form-control input-sm m-bot15'} %>

restaurant_waiter/app/views/super_admin/_restaurant_detail.html.erb
<label for="exampleInputEmail1">Restaurant</label>
<%= select_tag 'restaurantdetail_restaurant', options_for_select(@restaurants.collect{ |u| [u.restaurant_name, u.id] }), {:prompt => 'Select Restaurant', :class => 'form-control  input-sm m-bot15'} %>

restaurant_waiter/app/views/super_admin/ads.html.erb
<%= content_for :header do %>
    <%= javascript_include_tag 'super_admin', 'jquery.dataTables.min', 'DT_bootstrap.js','data-turbolinks-track' => true %>
<% end %>
<section class="panel">
  <header class="panel-heading">
    <strong>Control Ads</strong>
  </header>
  <div class="panel-body">
    <form role="form" class="cmxform" id="superadmin_adcontrol">
      <div class="form-group col-lg-3">
        <label for="exampleInputEmail1">Country</label>
        <%= country_select(:restaurantdetail, :country, {priority: %w(US CA), prompt: 'Select Country'}, :class => "form-control input-sm m-bot15") %>
      </div>
      <div class="form-group col-lg-3 ">
        <label for="exampleInputPassword1">State</label>
        <div id="country_state_code_wrapper">
        <%= render partial: 'admin/registrations/subregion_select', locals: {parent_region: ''} %>
        </div>
      </div>
      <div class="form-group col-lg-6" style="margin-top: 20px;">
        <label for="exampleInputPassword1"></label>
        <button type="button" class="btn btn-info" onclick="getrestaurantcity();">Get City</button>
      </div>
    </form>
  </div>
  <div class="panel-body">
    <form role="form">
      <div id="superadmin_getcities" class=" form-group col-lg-3"></div>
      <div id="superadmin_getrestaurantdetails" class=" form-group col-lg-3"></div>
    </form>
  </div>

</section>

<section class="panel">
  <header class="panel-heading">
    Ads Details
  </header>
  <div class="panel-body" id="super_admin_ad_details">
    <div class="adv-table">
    <%= render :partial => 'super_admin/ad_details' %>
    </div>
  </div>
</section>


<script>
    $(document).on('ready', function() {
        $('#superadmin_ads_table').dataTable({
            "iDisplayLength": 10,
            "sPaginationType": "bootstrap",
            "sDom": "<'row'<'col-lg-6'l><'col-lg-6'f>r>t<'row'<'col-lg-6'i><'col-lg-6'p>>",
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page",
                "oPaginate": {
                    "sPrevious": "Prev",
                    "sNext": "Next"
                }
            }
        });
        jQuery('#superadmin_ads_table_wrapper .dataTables_filter input').addClass("form-control medium"); // modify table search input
        jQuery('#superadmin_ads_table_wrapper .dataTables_length select').addClass("form-control xsmall"); // modify table per page dropdown
    });
</script>

restaurant_waiter/app/views/super_admin/customers.html.erb
<% content_for :header do %>
    <%= javascript_include_tag 'super_admin.js', 'jquery.dataTables.min', 'DT_bootstrap.js', 'data-turbolinks-track' => true %>
    <style>
        @media only screen and (min-width: 400px ) and (max-width: 1660px ){
            thead th{
                height: 50px !important;
            }
            tbody td{
                height: 50px !important;
            }
        }
        .button_to{
            background:none!important;
            border:none;
            padding:0!important;
            color:#069;
            cursor: pointer;
        }
        .button_to:hover{
            color:#000;
        }
    </style>
<% end %>
<section class="panel">
<header class="panel-heading">
  <strong>Our Customers</strong>
</header>
<div class="panel-body">
  <section id="flip-scroll">
<table  class="table table-bordered table-striped table-condensed cf dataTable" id="restaurantTable">
<thead class="cf">
<tr>
  <th>Restaurant Name</th>
  <th>Address </th>
  <th>Phone</th>
  <th>Email</th>
  <th>Registration Date</th>
  <th>Actions</th>
</tr>
</thead>
<tbody>
<% @restaurants.each do |restaurant| %>
<tr>
  <td>
    <% if @ec %>
        <%= link_to restaurant.restaurant_name, admin_session_path(:id => restaurant.id, :super_admin => true) ,:class => 'button_to', :target => "_blank", :method => 'post'%>
    <% else %>
    <%= restaurant.restaurant_name rescue '' %>
    <% end %>
   </td>
  <td><%= restaurant.address1 rescue ''%>,<br>&nbsp;<%= restaurant.address2%></td>
  <td><%= restaurant.phone1 rescue ''%>,<br>&nbsp;<%= restaurant.phone2 rescue '' %></td>
  <td><%= restaurant.restaurant_email rescue '' %></td>
  <td><%= restaurant.created_at.strftime("%Y-%m-%d") rescue '' %></td>
  <td>
    <% if @ec %>
        <% unless restaurant.admin.nil? %>
            <button id="update_admin_id" admin_id="<%=restaurant.admin.id rescue nil %>" type="button" class="btn btn-primary update_admin_id_<%= restaurant.admin.id %>"><%= restaurant.admin.active ? 'Disable' : 'Enable' %></button>
        <% end %>
    <% else %>
        <%= link_to 'Follow', "#", :class => "btn btn-warning" %>
    <% end %>
   </td>
</tr>
<% end %>
</tbody>
</table>
</section>
</div>
</section>
<script type="text/javascript">
    $(document).ready(function() {
        $('#restaurantTable').dataTable( {
            "iDisplayLength": 10,
            "sPaginationType": "bootstrap",
            "sDom": "<'row'<'col-lg-6'l><'col-lg-6'f>r>t<'row'<'col-lg-6'i><'col-lg-6'p>>",
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page",
                "oPaginate": {
                    "sPrevious": "Prev",
                    "sNext": "Next"
                }
            }
        } );
        jQuery('#restaurantTable_wrapper .dataTables_filter input').addClass("form-control medium"); // modify table search input
        jQuery('#restaurantTable_wrapper .dataTables_length select').addClass("form-control xsmall"); // modify table per page dropdown
    } );
</script>